### ISSUE TITLE
Does not work with Visual Studio 2019 Preview 2

### ISSUE THREAD

**Issue by sharwell** [pharring/EditorGuidelines#21]
See title. The context menu item is still present but guidelines do not appear.

Steps to reproduce added to https://github.com/pharring/EditorGuidelines/issues/21#issuecomment-488743002

**Comment by sharwell** [comment]
Looks like an exception was thrown:

```
A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "ColumnGuide.ColumnGuideAdornmentFactory". ---> System.ArgumentException: Object of type 'Microsoft.VisualStudio.CodingConventions.CodingConventionsManager' cannot be converted to type 'Microsoft.VisualStudio.CodingConventions.ICodingConventionsManager'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.SetImportingMember(Object part, MemberInfo member, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
```

**Comment by pharring** [comment]
@sharwell thanks.

**Comment by sharwell** [comment]
It looks like the issue is a breaking change in some part of Microsoft.VisualStudio.CodingConventions. I don't have a good way to fix this without breaking one or more supported versions:

* We can't omit **Microsoft.VisualStudio.CodingConventions.dll** from the VSIX altogether, or Visual Studio 2012-2015 will not be able to resolve the references to interfaces.
* We can't include **Microsoft.VisualStudio.CodingConventions.dll** in the VSIX without risking breaking Visual Studio 2017+, because the strong name of the assembly did not change when breaking API changes were made. In a mixed-version scenario, either the platform assembly will load and break this extension, or the assembly packaged with the extension will load and break the platform.

The most straightforward immediate solution is to remove this feature, at least for now.

**Comment by sharwell** [comment]
I am no longer able to repro or make sense of this bug.

**Comment by sharwell** [comment]
Steps to reproduce:

1. Create a C# project containing a source file **Class1.cs**
2. Install the following package:
    ```xml
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="3.1.0-beta1-19113-04" PrivateAssets="all" />
    ```
3. Close all documents and restart the IDE
4. Open the solution (no documents should be open)
5. Press <kbd>Ctrl</kbd>+<kbd>T</kbd>, type `f Class1.cs`, <kbd>Enter</kbd>

**Comment by pharring** [comment]
@sharwell is this still an issue?
I tried your repro steps, but I couldn't find that CodeStyle nuget package on nuget.org. Where can I get it?

**Comment by sharwell** [comment]
It's in this package source:

```
<add key="roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
```

**Comment by pharring** [comment]
Thanks. I couldn't repro on 16.0.4. Guidelines still work and I can add/remove them via the context menu.

I just got prompted to upgrade VS 2019 to 16.1.1, so I'll try again after that.

@sharwell can you still repro in your environment?

**Comment by sharwell** [comment]
Yes it doesn't repro every time but I can reproduce it some of the time.

**Comment by pharring** [comment]
Old issue. Not repro here. Possibly limited to projects that also depend on coding conventions.

**Comment by Prodigio** [comment]
Suddenly I encountered the same exception. On my side everytime I open up VS 2019 Version 16.9.6.

```
Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost

A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;EditorGuidelines.ColumnGuideAdornmentFactory&quot;. ---&gt;

System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;
at EditorGuidelines.ColumnGuideAdornmentFactory.OnImportsSatisfied()&#x000D;&#x000A;
--- End of inner exception stack trace ---&#x000D;&#x000A;
at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.InvokeOnImportsSatisfied()&#x000D;&#x000A;
at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.NotifyTransitiveImportsSatisfied()&#x000D;&#x000A;
at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;
at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;
at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;
at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()
```

**Comment by pharring** [comment]
@Prodigio thanks for the report. I'm tracking this in #85
