### ISSUE TITLE
Visual Studio 2022 Compatibility?

### ISSUE THREAD

**Issue by mjanofsky** [pharring/EditorGuidelines#92]
Received an error attempting to install in VS 2022.  Here is the log file contents:

12/15/2021 1:28:30 PM - Microsoft VSIX Installer
12/15/2021 1:28:30 PM - -------------------------------------------
12/15/2021 1:28:30 PM - vsixinstaller.exe version:
12/15/2021 1:28:30 PM - 17.0.5226-preview5
12/15/2021 1:28:30 PM - -------------------------------------------
12/15/2021 1:28:30 PM - Command line parameters:
12/15/2021 1:28:30 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\MattJanofsky\Downloads\EditorGuidelines.vsix
12/15/2021 1:28:30 PM - -------------------------------------------
12/15/2021 1:28:30 PM - Microsoft VSIX Installer
12/15/2021 1:28:30 PM - -------------------------------------------
12/15/2021 1:28:31 PM - Initializing Install...
12/15/2021 1:28:31 PM - Extension Details...
12/15/2021 1:28:31 PM - 	Identifier         : Editor_Guidelines.Microsoft Corp..123716ef-b2ed-4fab-bbcf-1d5f84856ca3
12/15/2021 1:28:31 PM - 	Name               : Editor Guidelines
12/15/2021 1:28:31 PM - 	Author             : Paul Harrington
12/15/2021 1:28:31 PM - 	Version            : 2.2.8
12/15/2021 1:28:31 PM - 	Description        : Adds vertical column guides to the Visual Studio text editor.
12/15/2021 1:28:31 PM - 	Locale             : en-US
12/15/2021 1:28:31 PM - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelines
12/15/2021 1:28:31 PM - 	InstalledByMSI     : False
12/15/2021 1:28:31 PM - 	SupportedFrameworkVersionRange : [4.5,)
12/15/2021 1:28:31 PM - 
12/15/2021 1:28:31 PM - 	SignatureState     : Unsigned
12/15/2021 1:28:31 PM - 	Supported Products : 
12/15/2021 1:28:31 PM - 		Microsoft.VisualStudio.Community
12/15/2021 1:28:31 PM - 			Version : [14.0,17.0)
12/15/2021 1:28:31 PM - 			ProductArchitecture : x86
12/15/2021 1:28:31 PM - 
12/15/2021 1:28:31 PM - 	References         : 
12/15/2021 1:28:31 PM - 	Prerequisites      : 
12/15/2021 1:28:31 PM - 		-------------------------------------------------------
12/15/2021 1:28:31 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/15/2021 1:28:31 PM - 		Name         : Visual Studio core editor
12/15/2021 1:28:31 PM - 		Version      : [15.0,)
12/15/2021 1:28:31 PM - 
12/15/2021 1:28:31 PM - Signature Details...
12/15/2021 1:28:31 PM - 	Extension is not signed.
12/15/2021 1:28:31 PM - 
12/15/2021 1:28:31 PM - Searching for applicable products...
12/15/2021 1:28:31 PM - Found installed product - Global Location
12/15/2021 1:28:31 PM - Found installed product - Visual Studio Professional 2022
12/15/2021 1:28:31 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by mjanofsky** [comment]
I see others have reported the same issue, only to later find it in the Extensions Manager.  Maybe update the documentation so we don't bother creating tickets?
