### ISSUE TITLE
VS2022 17.1.0 Preview 1.1 Package did not load correctly

### ISSUE THREAD

**Issue by RayKoopa** [pharring/EditorGuidelines#93]
This may mostly be some weird external / system setup issue, but I'll ask away in hope someone had a similar problem:

I'm on VS2022 Preview (as required to use some new net6.0-android features) and the extension does not display guidelines and only shows the following generic error and ActivityLog entries upon trying to manually add one via the editor context menu:

```
The 'EditorGuidelinesPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension.
You can get more information by examining the file
'C:\Users\Ray\AppData\Roaming\Microsoft\VisualStudio\17.0_5adf4668\ActivityLog.xml'.

Restarting Visual Studio could help resolve this issue.

Continue to show this error message? (Yes / No)
```

ActivityLog.xml:
```xml
<entry>
	<record>859</record>
	<time>2021/12/18 12:12:28.344</time>
	<type>Information</type>
	<source>VisualStudio</source>
	<description>Begin package load [EditorGuidelinesPackage]</description>
	<guid>{A0B80B01-BE16-4C42-AB44-7F8D057FAA2F}</guid>
</entry>
<entry>
	<record>860</record>
	<time>2021/12/18 12:12:28.352</time>
	<type>Error</type>
	<source>VisualStudio</source>
	<description>
SetSite failed for package [EditorGuidelinesPackage]Source: 'EditorGuidelines' Description: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at EditorGuidelines.EditorGuidelinesPackage.<InitializeAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at EditorGuidelines.EditorGuidelinesPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	</description>
	<guid>{A0B80B01-BE16-4C42-AB44-7F8D057FAA2F}</guid>
	<hr>80070002</hr>
	<errorinfo></errorinfo>
</entry>
<entry>
	<record>861</record>
	<time>2021/12/18 12:12:28.352</time>
	<type>Error</type>
	<source>VisualStudio</source>
	<description>End package load [EditorGuidelinesPackage]</description>
	<guid>{A0B80B01-BE16-4C42-AB44-7F8D057FAA2F}</guid>
	<hr>80070002</hr>
	<errorinfo></errorinfo>
</entry>ualStudio</source>
    <description>End package load [EditorGuidelinesPackage]</description>
    <guid>{A0B80B01-BE16-4C42-AB44-7F8D057FAA2F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
```

I am not sure why the `Microsoft.ApplicationInsights` isn't found. Shouldn't it be included with the extension, or even come preinstalled with VS2022 (I did not explicitly turn such a feature off nor can find it in the setup / extensions, the installation is "mostly" fresh / clean)? And if not, how would I usually get it?

**Comment by bddckr** [comment]
See #87. A workaround can be found in [this comment](https://github.com/pharring/EditorGuidelines/issues/87#issuecomment-965794495).

**Comment by RayKoopa** [comment]
Thanks! Solved it. Sorry, I didn't find that issue as I only checked open ones 🙈
